name: jobs seq exec order with sleep
on:
  workflow_dispatch:
jobs:
    job1:
     runs-on: ubuntu-latest
     steps:
        - name: job1 step1
          run: |
           echo "This is job 1 step 1"
           sleep 10
           

    job2:
     runs-on: ubuntu-latest
     needs: job1
     steps:
        - name: job2 step1
          run: |
           echo "This is job 2 step 1"
           sleep 10


    job3:
     runs-on: ubuntu-latest
     needs: job2
     steps:
        - name: job3 step1
          run: |
           echo "This is job 3 step 1"
           pwd