name: Multiple-job order-sequential-execution

on:
  workflow_dispatch:

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: list files after checkout
      run: ls -la
    - name: Creation of a file
      run: echo "HE IS SELF CENTERED PERSON" > kishore.txt   

  job2:
    name: Second Job
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Display list of files after job1
      run: ls -la

    - name: Creation of a file
      run: echo "HE IS HONEST PERSON" > gbr.txt 
    
  job3:
      name: Third Job
      runs-on: ubuntu-latest
      needs: job2
      steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Display list of files after job2
        run: ls -la

      - name: Display contents of files created in previous jobs
        run: cat kishore.txt gbr.txt