name: Testing WF  
on: push
jobs:
    test-job:
         runs-on: ubuntu-latest
         steps:
           - name: Hello Display
             run: echo "Hello INFO"
           - name: Date Display
             run: date
