name: Multiple-job order-sequential-execution-with-previous-job-files

on:
  workflow_dispatch:

jobs:
 job1:
  name: First Job
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v5

    - name: Create file
      run: echo "HE IS SELF CENTERED PERSON" > kishore.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: job1-files
        path: kishore.txt


 job2:
  name: Second Job
  runs-on: ubuntu-latest
  needs: job1

  steps:
    - uses: actions/checkout@v5

    - name: Download artifact from job1
      uses: actions/download-artifact@v4
      with:
        name: job1-files

    - name: Create another file
      run: echo "HE IS HONEST PERSON" > gbr.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: job2-files
        path: |
          kishore.txt
          gbr.txt

 job3:
  name: Third Job
  runs-on: ubuntu-latest
  needs: job2

  steps:
    - uses: actions/checkout@v5

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: job2-files

    - name: Display contents
      run: cat kishore.txt gbr.txt

