name: SSK

on:
  workflow_dispatch:

jobs:

  build-job:
    name: Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # If package.json is inside a folder, set working-directory
      - name: Install Dependencies
        run: npm install
        working-directory: frontend   # <-- change if needed

      - name: Build App
        run: npm run build
        working-directory: frontend   # <-- change if needed


  test-job:
    name: Testing Stage
    runs-on: ubuntu-latest
    needs: build-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: frontend   # <-- change if needed

      - name: Run Tests
        run: npm test
        working-directory: frontend   # <-- change if needed