name: Syatem-Info
on:
  push:
    branches:
    - main
#workflow_dispatch:

jobs:
  sys-info-job:
    name: System Information-Stage
    runs-on: ubuntu-latest

    steps:
    - name: Print-hostname
      run: hostname

    - name: Print-OS Information
      run: uname -a

    - name: Print-Disk Usage
      run: df -h

    - name: Kernal-Info
      run: uname -r

    - name: Show OS info
      run: cat /etc/os-release
